openapi: 3.2.0
info:
  contact:
    email: lxc-devel@lists.linuxcontainers.org
    name: Incus upstream
    url: https://github.com/lxc/incus
  description: 'This is the REST API used by all Incus clients.

    Internal endpoints aren''t included in this documentation.


    The Incus API is available over both a local unix+http and remote https API.

    Authentication for local users relies on group membership and access to the unix socket.

    For remote users, the default authentication method is TLS client

    certificates.'
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  title: Incus external REST Network Address Sets API
  version: '1.0'
tags:
- name: network-address-sets
paths:
  /1.0/network-address-sets:
    get:
      description: Returns a list of network address sets (URLs).
      operationId: network_address_sets_get
      parameters:
      - description: Project name
        example: default
        in: query
        name: project
        schema:
          type: string
      - description: Retrieve network address sets from all projects
        example: true
        in: query
        name: all-projects
        schema:
          type: boolean
      - description: Collection filter
        example: default
        in: query
        name: filter
        schema:
          type: string
      responses:
        '200':
          description: API endpoints
          content:
            application/json:
              schema:
                description: Sync response
                properties:
                  metadata:
                    description: List of endpoints
                    example: "[\n  \"/1.0/network-address-sets/foo\",\n  \"/1.0/network-address-sets/bar\"\n]"
                    items:
                      type: string
                    type: array
                  status:
                    description: Status description
                    example: Success
                    type: string
                  status_code:
                    description: Status code
                    example: 200
                    type: integer
                  type:
                    description: Response type
                    example: sync
                    type: string
                type: object
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Get the network address sets
      tags:
      - network-address-sets
    post:
      description: Creates a new network address set.
      operationId: network_address_sets_post
      parameters:
      - description: Project name
        example: default
        in: query
        name: project
        schema:
          type: string
      responses:
        '200':
          $ref: '#/components/responses/EmptySyncResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Add a network address set
      tags:
      - network-address-sets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetworkAddressSetsPost'
        description: address set
        required: true
  /1.0/network-address-sets/{name}:
    delete:
      description: Removes the network address set.
      operationId: network_address_set_delete
      parameters:
      - description: Address set name
        in: path
        name: name
        required: true
        schema:
          type: string
      - description: Project name
        example: default
        in: query
        name: project
        schema:
          type: string
      responses:
        '200':
          $ref: '#/components/responses/EmptySyncResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Delete the network address set
      tags:
      - network-address-sets
    get:
      description: Gets a specific network address set.
      operationId: network_address_set_get
      parameters:
      - description: Address set name
        in: path
        name: name
        required: true
        schema:
          type: string
      - description: Project name
        example: default
        in: query
        name: project
        schema:
          type: string
      responses:
        '200':
          description: address set
          content:
            application/json:
              schema:
                description: Sync response
                properties:
                  metadata:
                    $ref: '#/components/schemas/NetworkAddressSet'
                  status:
                    description: Status description
                    example: Success
                    type: string
                  status_code:
                    description: Status code
                    example: 200
                    type: integer
                  type:
                    description: Response type
                    example: sync
                    type: string
                type: object
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Get the network address set
      tags:
      - network-address-sets
    patch:
      description: Updates a subset of the network address set configuration.
      operationId: network_address_set_patch
      parameters:
      - description: Address set name
        in: path
        name: name
        required: true
        schema:
          type: string
      - description: Project name
        example: default
        in: query
        name: project
        schema:
          type: string
      responses:
        '200':
          $ref: '#/components/responses/EmptySyncResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '412':
          $ref: '#/components/responses/PreconditionFailed'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Partially update the network address set
      tags:
      - network-address-sets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetworkAddressSetPut'
        description: Address set configuration
        required: true
    post:
      description: Renames an existing network address set.
      operationId: network_address_set_post
      parameters:
      - description: Address set name
        in: path
        name: name
        required: true
        schema:
          type: string
      - description: Project name
        example: default
        in: query
        name: project
        schema:
          type: string
      responses:
        '200':
          $ref: '#/components/responses/EmptySyncResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Rename the network address set
      tags:
      - network-address-sets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetworkAddressSetPost'
        description: Address set rename request
        required: true
    put:
      description: Updates the entire network address set configuration.
      operationId: network_address_set_put
      parameters:
      - description: Address set name
        in: path
        name: name
        required: true
        schema:
          type: string
      - description: Project name
        example: default
        in: query
        name: project
        schema:
          type: string
      responses:
        '200':
          $ref: '#/components/responses/EmptySyncResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '412':
          $ref: '#/components/responses/PreconditionFailed'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Update the network address set
      tags:
      - network-address-sets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetworkAddressSetPut'
        description: Address set configuration
        required: true
  /1.0/network-address-sets?recursion=1:
    get:
      description: Returns a list of network address sets (structs).
      operationId: network_address_sets_get_recursion1
      parameters:
      - description: Project name
        example: default
        in: query
        name: project
        schema:
          type: string
      - description: Retrieve network address sets from all projects
        example: true
        in: query
        name: all-projects
        schema:
          type: boolean
      - description: Collection filter
        example: default
        in: query
        name: filter
        schema:
          type: string
      responses:
        '200':
          description: API endpoints
          content:
            application/json:
              schema:
                description: Sync response
                properties:
                  metadata:
                    description: List of network address sets
                    items:
                      $ref: '#/components/schemas/NetworkAddressSet'
                    type: array
                  status:
                    description: Status description
                    example: Success
                    type: string
                  status_code:
                    description: Status code
                    example: 200
                    type: integer
                  type:
                    description: Response type
                    example: sync
                    type: string
                type: object
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Get the network address sets
      tags:
      - network-address-sets
components:
  schemas:
    NetworkAddressSetPost:
      properties:
        name:
          description: The new name of the address set
          example: '"bar"'
          type: string
          x-go-name: Name
      title: NetworkAddressSetPost used for renaming an address set.
      type: object
      x-go-package: github.com/lxc/incus/v7/shared/api
    NetworkAddressSet:
      description: Refer to doc/howto/network_address_sets.md for details.
      properties:
        addresses:
          description: List of addresses in the set
          example:
          - 192.0.0.1
          - 2001:0db8:1234::1
          items:
            type: string
          type: array
          x-go-name: Addresses
        config:
          description: Address set configuration map (refer to doc/network-address-sets.md)
          example:
            user.mykey: foo
          type: object
          x-go-name: Config
        description:
          description: Description of the address set
          example: Web servers
          type: string
          x-go-name: Description
        name:
          description: The new name of the address set
          example: '"bar"'
          type: string
          x-go-name: Name
        project:
          description: Project name
          example: project1
          type: string
          x-go-name: Project
        used_by:
          description: List of URLs of objects using this profile
          example:
          - /1.0/network-acls/foo
          - /1.0/network-acls/bar
          - /1.0/network-acls/baz
          items:
            type: string
          readOnly: true
          type: array
          x-go-name: UsedBy
      title: NetworkAddressSet represents an address set.
      type: object
      x-go-package: github.com/lxc/incus/v7/shared/api
    NetworkAddressSetPut:
      properties:
        addresses:
          description: List of addresses in the set
          example:
          - 192.0.0.1
          - 2001:0db8:1234::1
          items:
            type: string
          type: array
          x-go-name: Addresses
        config:
          description: Address set configuration map (refer to doc/network-address-sets.md)
          example:
            user.mykey: foo
          type: object
          x-go-name: Config
        description:
          description: Description of the address set
          example: Web servers
          type: string
          x-go-name: Description
      title: NetworkAddressSetPut used for updating an address set.
      type: object
      x-go-package: github.com/lxc/incus/v7/shared/api
    NetworkAddressSetsPost:
      properties:
        addresses:
          description: List of addresses in the set
          example:
          - 192.0.0.1
          - 2001:0db8:1234::1
          items:
            type: string
          type: array
          x-go-name: Addresses
        config:
          description: Address set configuration map (refer to doc/network-address-sets.md)
          example:
            user.mykey: foo
          type: object
          x-go-name: Config
        description:
          description: Description of the address set
          example: Web servers
          type: string
          x-go-name: Description
        name:
          description: The new name of the address set
          example: '"bar"'
          type: string
          x-go-name: Name
      title: NetworkAddressSetsPost used for creating a new address set.
      type: object
      x-go-package: github.com/lxc/incus/v7/shared/api
  responses:
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            properties:
              error:
                example: not authorized
                type: string
                x-go-name: Error
              error_code:
                example: 403
                format: int64
                type: integer
                x-go-name: ErrorCode
              type:
                example: error
                type: string
                x-go-name: Type
            type: object
    PreconditionFailed:
      description: Precondition Failed
      content:
        application/json:
          schema:
            properties:
              error:
                example: precondition failed
                type: string
                x-go-name: Error
              error_code:
                example: 412
                format: int64
                type: integer
                x-go-name: ErrorCode
              type:
                example: error
                type: string
                x-go-name: Type
            type: object
    EmptySyncResponse:
      description: Empty sync response
      content:
        application/json:
          schema:
            properties:
              status:
                example: Success
                type: string
                x-go-name: Status
              status_code:
                example: 200
                format: int64
                type: integer
                x-go-name: StatusCode
              type:
                example: sync
                type: string
                x-go-name: Type
            type: object
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            properties:
              error:
                example: bad request
                type: string
                x-go-name: Error
              error_code:
                example: 400
                format: int64
                type: integer
                x-go-name: ErrorCode
              type:
                example: error
                type: string
                x-go-name: Type
            type: object
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            properties:
              error:
                example: internal server error
                type: string
                x-go-name: Error
              error_code:
                example: 500
                format: int64
                type: integer
                x-go-name: ErrorCode
              type:
                example: error
                type: string
                x-go-name: Type
            type: object
